services:
  mongodb:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ikinwotezekiel_db_user
      MONGO_INITDB_ROOT_PASSWORD: Or62Zbn5xGffJmGI
      MONGO_INITDB_DATABASE: bank_loan_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
