services:
  app:
    build: .
    ports:
      - "8080:80"
    env_file: .env
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: bank_loan_db
      MYSQL_ROOT_PASSWORD: your_secure_password
      # Remove MYSQL_USER: root
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Optionally keep this if you want no root password (not recommended for production)
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: