services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - MONGODB_URI=mongodb+srv://ikinwotezekiel_db_user:Or62Zbn5xGffJmGI@bank-secure-1.kaw3lal.mongodb.net/bank_loan_db?retryWrites=true&w=majority
      - DB_DATABASE=bank_loan_db
    depends_on:
      - mongodb
    volumes:
      - .:/var/www/html

  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_DATABASE: bank_loan_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: