services:
  php-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/bank_loan_db
      - DB_DATABASE=bank_loan_db
      - PORT=8080
      - APP_ENV=development
      - APP_DEBUG=true
    depends_on:
      - mongo
    volumes:
      - ./:/var/www/html
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devuser
      - MONGO_INITDB_ROOT_PASSWORD=devpass
      - MONGO_INITDB_DATABASE=bank_loan_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
