version: '3.8'

services:
  app:
    build: .
    ports:
      - "${APP_PORT}:80"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - DB_DATABASE=${DB_DATABASE}
    depends_on:
      - mongodb
    volumes:
      - .:/var/www/html

  mongodb:
    image: mongo:6.0
    environment:
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
