services:
  php-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=bank_loan_db
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpass
      - PORT=8080
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=devpass
      - MYSQL_DATABASE=bank_loan_db
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: